"""Add email column to Student

Revision ID: 37402f28dba0
Revises: a6c22725d27e
Create Date: 2025-10-22 13:19:17.456429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37402f28dba0'
down_revision = 'a6c22725d27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
